### ISSUE TITLE
Blank screen for new app, and no hot-reloading

### ISSUE THREAD

**Issue by Ibcs16** [cawfree/create-react-native-dapp#16] opened 2021-10-23 20:46 UTC
- **I'm submitting a ...**
  [X ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I don't why, but Ive tried to setup a project many times now, and all I get is a blank screen. It also never hot-reload when I change something in App file. Dont have a clue why!?

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
- Run```npx create-react-native-dapp``` command
- Run ```yarn start```
Gives a blank screen and nothing else

**Comment by cawfree** [comment] 2021-10-28 12:40
Hello, this looks like a duplicate of #17, so I'm going to close this issue in the hope that we can continue discussion there.

**Closed as completed by cawfree** 2021-10-28 12:40 UTC

**Comment by blixit** [comment] 2021-11-11 22:11
Hello,
I allow myself to comment this closed thread because I think this error is not #17 related. I hope my analysis is right if not I apologize for adding confusion.

I also add this comment because my resolution step is reproductible. Fixing the warnings about the version of @react-native-async-storage/async-storage and react-native-get-random-values helped to resolve the problem.

**Local Context**:
- MacOS 12
- Xcode 13
- node 12 (by the way, it should be explicit in the readme)
- yarn 1.22.10
- expo 4.13.0

After installation, running `expo start` led me to a blank screen on my iOS simulator running expoGo:

| iOS 15 simulator        | expo start warning           |
| ------------- |:-------------:| 
| ![image](https://user-images.githubusercontent.com/6025710/141374786-1e9bb016-72ff-42a0-80c4-6e579263611e.png)   | <img width="438" alt="image" src="https://user-images.githubusercontent.com/6025710/141374847-5e9bf494-d772-4417-b91f-af6ec9fc8610.png">  |

I first ignored the warnings by trying many other solutions like ejecting Expo. I felt I was leaving the solution behind me. Then I tried to fix the warnings.

I upgraded all the libraries. It turns out that using the react-native-svg@12.1.1 introduced a conflict with WallectConnect internal configuration. So I decided to rollback to 9.6.4 but keeping upgraded the versions of @react-native-async-storage/async-storage and react-native-get-random-values.

That's the way I fixed up the white screen issue

![image](https://user-images.githubusercontent.com/6025710/141375797-a4b92aef-b891-4515-aeeb-3365fcd5d2f9.png)

**Comment by dparker2** [comment] 2021-12-31 18:29
seconded, upgrading both `react-native-get-random-values` and `@react-native-async-storage/async-storage` fixes this issue for me too

**Comment by demayaa** [comment] 2022-02-27 13:05
@blixit thanks bro
